@extends('dashboard.layouts.reports')

@section('reports-content')
<div class="app-title">
  <div>
    <h1><i class="fa fa-trending-up"></i> Revenue Forecast Report</h1>
    <p>Predict future revenue based on historical trends</p>
  </div>
  <ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('admin.reports.index') }}">Reports</a></li>
    <li class="breadcrumb-item"><a href="#">Revenue Forecast</a></li>
  </ul>
</div>

@include('dashboard.reports.partials.receipt-styles')

<div class="receipt-report-container">
    <div class="receipt-report-header">
        <div class="logo-container">
            <div class="logo-text-brand" style="margin-bottom: 10px; display: inline-block;"><div style="background: #940000; color: white; width: 40px; height: 40px; border-radius: 6px; display: flex; align-items: center; justify-content: center; font-size: 24px; font-weight: bold;">U</div></div>
        </div>
        <h1>Umoja Lutheran Hostel</h1>
        <div style="margin-top: 10px; margin-bottom: 10px; line-height: 1.8;">
            <p style="margin: 5px 0; font-size: 13px; color: #555;">
                <strong>Location:</strong> Sokoine Road-Moshi Kilimanjaro-Tanzania
            </p>
            <p style="margin: 5px 0; font-size: 13px; color: #555;">
                <strong>Mobile/WhatsApp:</strong> 0677-155-156 / +255 677-155-157
            </p>
            <p style="margin: 5px 0; font-size: 13px; color: #555;">
                <strong>Email:</strong> info@Umoja Lutheran Hostelhotel.co.tz / infoUmoja Lutheran Hostelhotel@gmail.com
            </p>
        </div>
        <p style="margin-top: 15px; font-size: 16px; font-weight: bold; color: #e07632;">Revenue Forecast Report</p>
    </div>
    
    <div class="receipt-report-number">
        <strong>Report #:</strong> FORECAST-RPT-{{ date('Ymd') }}-{{ strtoupper(substr(md5('forecast' . now()), 0, 6)) }}
    </div>
    
    <div class="receipt-report-title">
        REVENUE FORECAST REPORT
    </div>
    
    <div class="print-button-section">
        <button onclick="printReport()">
            <i class="fa fa-print"></i> Print / Save as PDF
        </button>
        <div style="font-size: 11px; color: #333; margin-top: 10px; background: #fff3cd; padding: 10px; border-radius: 4px; border-left: 3px solid #ffc107;">
            <strong><i class="fa fa-info-circle"></i> Important:</strong> To remove URLs and headers from the printed report:<br>
            <strong>Chrome/Edge:</strong> In print dialog → More settings → Uncheck "Headers and footers"<br>
            <strong>Firefox:</strong> In print dialog → More Settings → Headers & Footers → Select "--blank--"<br>
            <strong>Safari:</strong> In print options → Uncheck "Print headers and footers"
        </div>
    </div>
    
    <div class="receipt-two-column">
        <div class="receipt-column">
            <div class="receipt-info-section">
                <h3>Report Information</h3>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Report Type:</span>
                    <span class="receipt-info-value"><strong>Forecast Analysis</strong></span>
                </div>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Analysis Period:</span>
                    <span class="receipt-info-value">Last 6 Months</span>
                </div>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Generated on:</span>
                    <span class="receipt-info-value">{{ \Carbon\Carbon::now()->format('F d, Y \a\t g:i A') }}</span>
                </div>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Generated by:</span>
                    <span class="receipt-info-value">{{ $userName }} ({{ $userRole }})</span>
                </div>
            </div>
        </div>
        
        <div class="receipt-column">
            <div class="receipt-info-section">
                <h3>Current Status</h3>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Current Month Revenue:</span>
                    <span class="receipt-info-value" style="color: #28a745;"><strong>{{ number_format($currentMonthRevenueTZS, 0) }} TZS</strong></span>
                </div>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Projected Month Revenue:</span>
                    <span class="receipt-info-value" style="color: #e07632; font-size: 16px;"><strong>{{ number_format($projectedCurrentMonthRevenue, 0) }} TZS</strong></span>
                </div>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Average Growth Rate:</span>
                    <span class="receipt-info-value" style="color: {{ $averageGrowthRate >= 0 ? '#28a745' : '#dc3545' }};"><strong>{{ $averageGrowthRate >= 0 ? '+' : '' }}{{ $averageGrowthRate }}%</strong></span>
                </div>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Booking Pipeline:</span>
                    <span class="receipt-info-value">{{ $upcomingBookingsCount }} bookings</span>
                </div>
                <div class="receipt-info-row">
                    <span class="receipt-info-label">Pipeline Revenue:</span>
                    <span class="receipt-info-value" style="color: #17a2b8;">{{ number_format($pipelineRevenueTZS, 0) }} TZS</span>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Historical Revenue -->
    <div class="receipt-info-section">
        <h3>Historical Revenue (Last 6 Months)</h3>
        <table class="receipt-details-table">
            <thead>
                <tr>
                    <th>Month</th>
                    <th style="text-align: center;">Bookings</th>
                    <th style="text-align: right;">Revenue (TZS)</th>
                </tr>
            </thead>
            <tbody>
                @foreach($historicalRevenue as $month)
                <tr>
                    <td><strong>{{ $month['month'] }}</strong></td>
                    <td style="text-align: center;">{{ $month['bookings'] }}</td>
                    <td style="text-align: right;">{{ number_format($month['revenue'], 0) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
    <!-- Revenue Forecast -->
    <div class="receipt-info-section">
        <h3>Revenue Forecast (Next 3 Months)</h3>
        <table class="receipt-details-table">
            <thead>
                <tr>
                    <th>Month</th>
                    <th style="text-align: right;">Forecasted Revenue (TZS)</th>
                    <th style="text-align: center;">Confidence Level</th>
                </tr>
            </thead>
            <tbody>
                @foreach($forecast as $item)
                <tr>
                    <td><strong>{{ $item['month'] }}</strong></td>
                    <td style="text-align: right; color: #e07632; font-size: 14px;"><strong>{{ number_format($item['revenue'], 0) }}</strong></td>
                    <td style="text-align: center;">
                        @if($item['confidence'] == 'High')
                            <span style="color: #28a745; font-weight: bold;">{{ $item['confidence'] }}</span>
                        @elseif($item['confidence'] == 'Medium')
                            <span style="color: #ffc107; font-weight: bold;">{{ $item['confidence'] }}</span>
                        @else
                            <span style="color: #dc3545; font-weight: bold;">{{ $item['confidence'] }}</span>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
    <!-- Recommendations -->
    @if($averageGrowthRate < 0)
    <div class="recommendation-box danger">
        <h4><i class="fa fa-exclamation-triangle"></i> Declining Revenue Trend</h4>
        <p>Average growth rate is {{ $averageGrowthRate }}%, indicating a declining trend. Consider reviewing pricing strategies, marketing efforts, and operational efficiency.</p>
    </div>
    @elseif($averageGrowthRate > 10)
    <div class="recommendation-box success">
        <h4><i class="fa fa-check-circle"></i> Strong Growth Trend</h4>
        <p>Excellent growth rate of {{ $averageGrowthRate }}%. Maintain current strategies and consider expansion opportunities.</p>
    </div>
    @else
    <div class="recommendation-box info">
        <h4><i class="fa fa-info-circle"></i> Stable Growth</h4>
        <p>Growth rate of {{ $averageGrowthRate }}% indicates stable performance. Continue monitoring and optimize operations for better results.</p>
    </div>
    @endif
    
    @if($pipelineRevenueTZS > 0)
    <div class="recommendation-box info">
        <h4><i class="fa fa-calendar"></i> Booking Pipeline</h4>
        <p>You have {{ $upcomingBookingsCount }} upcoming bookings with expected revenue of {{ number_format($pipelineRevenueTZS, 0) }} TZS. This provides good visibility for near-term revenue.</p>
    </div>
    @endif
    
    <div class="receipt-footer">
        <p><strong>Umoja Lutheran Hostel</strong></p>
        <p>This forecast is based on historical data and trends. Actual results may vary.</p>
        <p style="margin-top: 15px;">This is an official report. Please keep this for your records.</p>
        <p style="margin-top: 10px; font-size: 9px;">Generated on: {{ now()->format('F d, Y \a\t g:i A') }}</p>
        <p class="powered-by">Powered By <strong>EmCa Technologies</strong></p>
    </div>
</div>

@endsection

@section('scripts')
<script>
function printReport() {
  window.print();
}
</script>
@endsection

